name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: PHPUnit
        with:
          version: 9.6.11
          php_extensions: "xdebug"
          bootstrap: tst/Bootstrap.php
          configuration: phpunit.xml
          args: --coverage-text
