name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3

        env:
          TEST_NAME: PHPUnit
          XDEBUG_MODE : coverage
        with:
          version: 9.6.11
          php_extensions: "xdebug gd"
          bootstrap: tst/Bootstrap.php
          configuration: phpunit.xml
          coverage_cobertura : cobertura.xml

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '50 80'

      - name: Markdown Report
        run : cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
