name: SCP

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy to SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        source: ${{ secrets.SOURCE }}
        port: ${{ secrets.PORT }}
        target: ${{ secrets.TARGET }}
        key: ${{ secrets.KEY }}
