name: SCP

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy to SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ec2-35-180-174-115.eu-west-3.compute.amazonaws.com
        username: ec2-user
        source: ./
        target: /var/www/html
        key: ${{ secrets.KEY }}
